### ISSUE TITLE
Separate movie list by availablility

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/Moviebase#3]
Movie list should be separated by its status _(ex:  Available/Not Available)_ in Server Database.

this caused many error when the folder have high density movie folder.

**Comment by fahminlb33** [comment]
#4

**Comment by fahminlb33** [comment]
Improvement on #4

**Comment by fahminlb33** [comment]
Based on current implementation in DataGridView, I think this is almost impossible. Current breakthrough is using different color to identify movie availability.
